
var drugInStorage={
	url:{
		//页面路径
		homePage:"/drugInStorage/home",
		newPage:"/drugInStorage/new",
		editPage:"/drugInStorage/edit/",
		viewPage:"/drugInStorage/view/",
		//数据请求路径
		list:"/drugInStorage/list/",
		getByInfo:"/drugInStorage/getByInfo",
		add:"/drugInStorage/add",
		update:"/drugInStorage/update",
		del:"/drugInStorage/del/"
	},
	list:function(data,callback){
		ajaxService.postAjax(this.url.list+data.pageNum+"/"+data.pageSize,data.params,function(data_){
			if(callback){
				callback(data_);
			}
		});
	},
	getByInfo:function(data,callback){
		ajaxService.postAjax(this.url.getByInfo,data,function(data_){
			if(data_.result==resultMesage.sucess){
				var msg=(data_.data);
				$("[name=id]").val(msg.id);
				$("[name=inStorageCode]").val(msg.inStorageCode);
				$("[name=orderId]").val(msg.orderId);
				$("[name=orderCode]").val(msg.orderCode);
				$("[name=registrationTime]").val(msg.registrationTimeStr);
				$("[name=buyer]").val(msg.buyer);
				$("[name=buyerName]").val(msg.buyerName);
				$("[name=status]").val(msg.status);
				$("[name=approveStatus]").val(msg.approveStatus);
				$("[name=deleteFlag]").val(msg.deleteFlag);
				callback(data_);
			}else{
				//返回错误时提示
			}
		});
	},
	add:function(data,callback){
		ajaxService.postAjax(this.url.add,data,function(data_){
			if(callback){
				callback(data_);
			}
		});
	},
	update:function(data,callback){
		ajaxService.postAjax(this.url.update,data,function(data_){
			if(callback){
				callback(data_);
			}
		});
	},
	del:function(id,callback){
		ajaxService.getAjax(this.url.del+id,null,function(data_){
			if(callback){
				callback(data_);
			}
		});
	}
};

/**
 * 删除数据行
 */
function delDrugInStorageRow(obj){
	delFromListOneRow(obj,1);
}
