
var drugOrder={
	url:{
		//页面路径
		homePage:"/drugOrder/home",
		newPage:"/drugOrder/new",
		editPage:"/drugOrder/edit/",
		viewPage:"/drugOrder/view/",
		//数据请求路径
		list:"/drugOrder/list/",
		getByInfo:"/drugOrder/getByInfo",
		add:"/drugOrder/add",
		update:"/drugOrder/update",
		del:"/drugOrder/del/"
	},
	list:function(data,callback){
		ajaxService.postAjax(this.url.list+data.pageNum+"/"+data.pageSize,data.params,function(data_){
			if(callback){
				callback(data_);
			}
		});
	},
	getByInfo:function(data,callback){
		ajaxService.postAjax(this.url.getByInfo,data,function(data_){
			if(data_.result==resultMesage.sucess){
				var msg=(data_.data);
				$("[name=id]").val(msg.id);
				$("[name=orderCode]").val(msg.orderCode);
				$("[name=department]").val(msg.department);
				$("[name=departmentName]").val(msg.departmentName);
				$("[name=applicant]").val(msg.applicant);
				$("[name=applicantName]").val(msg.applicantName);
				$("[name=applicantTime]").val(msg.applicantTimeStr);
				$("[name=approveStatus]").val(msg.approveStatus);
				$("[name=inventoryStatus]").val(msg.inventoryStatus);
				$("[name=deleteFlag]").val(msg.deleteFlag);
				callback(data_);
			}else{
				//返回错误时提示
			}
		});
	},
	add:function(data,callback){
		ajaxService.postAjax(this.url.add,data,function(data_){
			if(callback){
				callback(data_);
			}
		});
	},
	update:function(data,callback){
		ajaxService.postAjax(this.url.update,data,function(data_){
			if(callback){
				callback(data_);
			}
		});
	},
	del:function(id,callback){
		ajaxService.getAjax(this.url.del+id,null,function(data_){
			if(callback){
				callback(data_);
			}
		});
	}
};

/**
 * 删除数据行
 */
function delDrugOrderRow(obj){
	delFromListOneRow(obj,1);
}
